"""Generate the requirements-to-tests traceability matrix.

Inspired by critical-systems QA practice (ESA/CNES): every requirement must map
to at least one test, and every test must declare which requirement it covers.

The matrix is built from live data -- it collects the `@pytest.mark.req(...)`
markers actually present in the suite (via pytest collection) and cross-checks
them against the requirements registry (docs/requirements.json). It then writes:

    docs/traceability_matrix.md
    docs/traceability_matrix.csv

Usage:
    python scripts/gen_traceability.py            # write the matrix
    python scripts/gen_traceability.py --check     # fail if files are stale

The --check mode is what CI runs so the matrix can never silently drift.
"""

from __future__ import annotations

import csv
import io
import json
import sys
from collections import defaultdict
from pathlib import Path

import pytest

ROOT = Path(__file__).resolve().parent.parent
REGISTRY_PATH = ROOT / "docs" / "requirements.json"
MD_PATH = ROOT / "docs" / "traceability_matrix.md"
CSV_PATH = ROOT / "docs" / "traceability_matrix.csv"

LAYER_MARKERS = {"ui", "api", "unit", "bdd"}
LEVEL_MARKERS = {"smoke", "regression"}


class _MarkerCollector:
    """Pytest plugin that records req markers per collected test."""

    def __init__(self) -> None:
        # req_id -> {nodeids, levels}
        self.coverage: dict[str, dict] = defaultdict(lambda: {"nodeids": [], "levels": set()})

    def pytest_collection_modifyitems(self, items):
        for item in items:
            req_ids = [m.args[0] for m in item.iter_markers(name="req") if m.args]
            levels = {m.name for m in item.iter_markers()} & LEVEL_MARKERS
            for req_id in req_ids:
                self.coverage[req_id]["nodeids"].append(item.nodeid)
                self.coverage[req_id]["levels"] |= levels


def collect_coverage() -> dict[str, dict]:
    collector = _MarkerCollector()
    code = pytest.main(
        ["--collect-only", "-qq", "-p", "no:cacheprovider", "-o", "addopts="],
        plugins=[collector],
    )
    if code not in (0, pytest.ExitCode.OK):
        print(f"pytest collection failed (exit {code})", file=sys.stderr)
        sys.exit(1)
    return dict(collector.coverage)


def build_rows(registry: dict, coverage: dict) -> list[dict]:
    rows = []
    for req_id, meta in registry.items():
        cov = coverage.get(req_id)
        nodeids = sorted(cov["nodeids"]) if cov else []
        levels = ", ".join(sorted(cov["levels"])) if cov and cov["levels"] else "-"
        rows.append(
            {
                "req_id": req_id,
                "layer": meta["layer"],
                "description": meta["description"],
                "levels": levels,
                "test_count": len(nodeids),
                "tests": nodeids,
                "status": "COVERED" if nodeids else "GAP",
            }
        )
    rows.sort(key=lambda r: r["req_id"])
    return rows


def find_orphans(registry: dict, coverage: dict) -> list[str]:
    """req markers used in tests but absent from the registry."""
    return sorted(set(coverage) - set(registry))


def render_markdown(rows: list[dict], orphans: list[str]) -> str:
    covered = sum(1 for r in rows if r["status"] == "COVERED")
    total = len(rows)
    pct = (covered / total * 100) if total else 0
    out = io.StringIO()
    out.write("# Requirements Traceability Matrix\n\n")
    out.write(
        "> Auto-generated by `scripts/gen_traceability.py` from the live test "
        "suite. Do not edit by hand.\n\n"
    )
    out.write(
        f"**Coverage:** {covered}/{total} requirements covered ({pct:.0f}%) "
        f"&nbsp;|&nbsp; **Gaps:** {total - covered} "
        f"&nbsp;|&nbsp; **Orphan tests:** {len(orphans)}\n\n"
    )
    out.write("| Req ID | Layer | Requirement | Test level | # | Status | Test(s) |\n")
    out.write("|---|---|---|---|---|---|---|\n")
    for r in rows:
        tests = "<br>".join(f"`{t}`" for t in r["tests"]) or "—"
        out.write(
            f"| {r['req_id']} | {r['layer']} | {r['description']} | {r['levels']} "
            f"| {r['test_count']} | {r['status']} | {tests} |\n"
        )
    if orphans:
        out.write("\n## ⚠️ Orphan tests (req marker not in registry)\n\n")
        for o in orphans:
            out.write(f"- `{o}`\n")
    return out.getvalue()


def render_csv(rows: list[dict]) -> str:
    out = io.StringIO()
    # Force "\n" so the generated CSV matches the git-stored file on every OS
    # (csv.writer defaults to "\r\n", which never round-trips through git).
    writer = csv.writer(out, lineterminator="\n")
    writer.writerow(
        ["Req ID", "Layer", "Requirement", "Test level", "Test count", "Status", "Tests"]
    )
    for r in rows:
        writer.writerow(
            [
                r["req_id"],
                r["layer"],
                r["description"],
                r["levels"],
                r["test_count"],
                r["status"],
                " | ".join(r["tests"]),
            ]
        )
    return out.getvalue()


def main() -> int:
    check = "--check" in sys.argv
    registry = json.loads(REGISTRY_PATH.read_text())
    coverage = collect_coverage()
    rows = build_rows(registry, coverage)
    orphans = find_orphans(registry, coverage)

    md = render_markdown(rows, orphans)
    csv_text = render_csv(rows)

    if check:
        stale = (
            not MD_PATH.exists()
            or MD_PATH.read_text() != md
            or not CSV_PATH.exists()
            or CSV_PATH.read_text() != csv_text
        )
        if stale:
            print(
                "Traceability matrix is out of date. Run "
                "`python scripts/gen_traceability.py` and commit the result.",
                file=sys.stderr,
            )
            return 1
        print("Traceability matrix is up to date.")
        return 0

    MD_PATH.write_text(md)
    CSV_PATH.write_text(csv_text)
    gaps = [r["req_id"] for r in rows if r["status"] == "GAP"]
    print(f"Wrote {MD_PATH.relative_to(ROOT)} and {CSV_PATH.relative_to(ROOT)}")
    print(f"Requirements: {len(rows)} | Gaps: {gaps or 'none'} | Orphans: {orphans or 'none'}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
